apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
     containers:
     - name: user-service
       image: your-registry/user-service:latest
       ports:
       - containerPort: 8000
       env:
       - name: DATABASE_UR
          value: "postgresql://user:pass@user-db/userdb"